import { IntakeFormTableData } from '@/types';

export const intakeForms: IntakeFormTableData[] = [
  {
    id: '001',
    name: 'John Doe',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 2, 28, 14, 30),
  },
  {
    id: '002',
    name: 'Jane Smith',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 29, 9, 15),
  },
  {
    id: '003',
    name: 'Michael Johnson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 2, 30, 16, 45),
    flagged: true,
  },
  {
    id: '004',
    name: 'Emily Davis',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 3, 2, 11, 20),
  },
  {
    id: '005',
    name: 'Daniel Martinez',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 3, 8, 50),
  },
  {
    id: '006',
    name: 'Sarah Wilson',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 28, 14, 10),
  },
  {
    id: '007',
    name: 'David Anderson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 2, 31, 17, 5),
  },
  {
    id: '008',
    name: 'Olivia Thomas',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 3, 1, 10, 40),
  },
  {
    id: '009',
    name: 'James Taylor',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 4, 13, 25),
  },
  {
    id: '010',
    name: 'Isabella Moore',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 27, 15, 35),
  },
  {
    id: '011',
    name: 'William Jackson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 5, 9, 55),
  },
  {
    id: '012',
    name: 'Sophia Lee',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 26, 12, 30),
  },
];
