import { IntakeFormTableData } from '@/types';

export const intakeForms: IntakeFormTableData[] = [
  {
    id: '001',
    name: 'John Doe',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 2, 28, 14, 30),
  },
  {
    id: '002',
    name: 'Jane Smith',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 29, 9, 15),
  },
  {
    id: '003',
    name: 'Michael Johnson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 2, 30, 16, 45),
    flagged: true,
  },
  {
    id: '004',
    name: 'Emily Davis',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 3, 2, 11, 20),
  },
  {
    id: '005',
    name: 'Daniel Martinez',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 3, 8, 50),
  },
  {
    id: '006',
    name: 'Sarah Wilson',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 28, 14, 10),
  },
  {
    id: '007',
    name: 'David Anderson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 2, 31, 17, 5),
  },
  {
    id: '008',
    name: 'Olivia Thomas',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 3, 1, 10, 40),
  },
  {
    id: '009',
    name: 'James Taylor',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 4, 13, 25),
  },
  {
    id: '010',
    name: 'Isabella Moore',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 27, 15, 35),
  },
  {
    id: '011',
    name: 'William Jackson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 5, 9, 55),
  },
  {
    id: '012',
    name: 'Sophia Lee',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 26, 12, 30),
  },
  {
    id: '013',
    name: 'Ethan Brown',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 6, 11, 40),
  },
  {
    id: '014',
    name: 'Ava Garcia',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 25, 16, 20),
  },
  {
    id: '015',
    name: 'Alexander Rodriguez',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 7, 14, 55),
  },
  {
    id: '016',
    name: 'Mia Williams',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 24, 9, 30),
  },
  {
    id: '017',
    name: 'Benjamin Jones',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 8, 17, 10),
  },
  {
    id: '018',
    name: 'Charlotte Miller',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 23, 13, 45),
  },
  {
    id: '019',
    name: 'Henry Davis',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 9, 10, 20),
  },
  {
    id: '020',
    name: 'Amelia Wilson',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 22, 15, 50),
  },
  {
    id: '021',
    name: 'Samuel Anderson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 10, 8, 35),
  },
  {
    id: '022',
    name: 'Evelyn Thomas',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 21, 11, 15),
  },
  {
    id: '023',
    name: 'Joseph Jackson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 11, 16, 0),
  },
  {
    id: '024',
    name: 'Abigail White',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 20, 14, 25),
  },
  {
    id: '025',
    name: 'Daniel Harris',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 12, 9, 40),
  },
  {
    id: '026',
    name: 'Madison Martin',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 19, 12, 55),
  },
  {
    id: '027',
    name: 'Christopher Thompson',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 13, 17, 30),
  },
  {
    id: '028',
    name: 'Elizabeth Garcia',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 18, 10, 10),
  },
  {
    id: '029',
    name: 'Matthew Martinez',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 14, 13, 45),
  },
  {
    id: '030',
    name: 'Grace Robinson',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 17, 15, 20),
  },
  {
    id: '031',
    name: 'Andrew Clark',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 15, 11, 50),
  },
  {
    id: '032',
    name: 'Chloe Rodriguez',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 16, 9, 0),
  },
  {
    id: '033',
    name: 'Victoria Lewis',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 16, 14, 15), // Month is 0-indexed, so 3 is April
  },
  {
    id: '034',
    name: 'Ryan Walker',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 15, 16, 30), // Month is 0-indexed, so 2 is March
  },
  {
    id: '035',
    name: 'Natalie Hall',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 17, 10, 5),
    flagged: true,
  },
  {
    id: '036',
    name: 'Kevin Allen',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 14, 12, 40),
  },
  {
    id: '037',
    name: 'Lily Young',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 18, 8, 20),
  },
  {
    id: '038',
    name: 'Brandon Hernandez',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 13, 17, 55),
  },
  {
    id: '039',
    name: 'Zoey King',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 19, 15, 10),
  },
  {
    id: '040',
    name: 'Justin Wright',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 12, 11, 25),
  },
  {
    id: '041',
    name: 'Hannah Lopez',
    status: 'pending',
    type: 'Intake form',
    date: new Date(2025, 3, 20, 13, 35),
    flagged: true,
  },
  {
    id: '042',
    name: 'Tyler Hill',
    status: 'submitted',
    type: 'Intake form',
    date: new Date(2025, 2, 11, 9, 45),
  },
];
